version: "3.8"

services:
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    restart: always

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      - PG_USER=${PG_USER}
      - PG_HOST=database
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=5432
      - BACKEND_PORT=3000
      - FRONTEND_IP=${FRONTEND_IP}
      - SESSION_KEY=${SESSION_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_PRIVATE_KEY=${STRIPE_PRIVATE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_IP=${BACKEND_IP}
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
